#!/bin/sh

# --- Stops the script if errors are encountered. ---
set -e
# ---
#
# --- Based Off of/Ripped from https://github.com/FasterMelee/FasterMelee-installer/ Thank you Faster Melee Team!
# ---

if [ -f "./setup" ] && [ -z "${IN_NIX_SHELL++}" ]; then
	echo "You are running a hosted copy of the script. Please *delete the local file 'setup'* and run"
	echo ""
	echo "sh -c \"\$(curl -Ls https://raw.githubusercontent.com/Koopabro/Wagabuild-Installer/master/setup)"
	echo ""
	echo "to ensure you have the latest version!"
	exit
fi

# --- Attempts to determine the number of cores in the CPU. ---
# Source: https://gist.github.com/jj1bdx/5746298
# Linux and similar...
CPUS=$(getconf _NPROCESSORS_ONLN 2>/dev/null)
# FreeBSD and similar...
[ -z "$CPUS" ] && CPUS=$(getconf NPROCESSORS_ONLN)
# Solaris and similar...
[ -z "$CPUS" ] && CPUS=$(ksh93 -c 'getconf NPROCESSORS_ONLN')
# Give up...
[ -z "$CPUS" ] && CPUS=1
# ---

# --- define custom config links here!
WBVERSION="deluxe"
CONFIGNAME="wagabuild"
COMMITHASH="e07b514b6244913dbe14aa6949ff68f5775bfa4a"
CONFIGLINK="https://github.com/Koopabro/Wagabuild-Installer/raw/master/config/$WBVERSION-$CONFIGNAME.tar.gz"
GITCLONELINK="https://github.com/dolphin-emu/dolphin"
# ---

# --- delete all "Wagabuild" folders filled with incomplete installations
echo ""
echo "Attempting to delete incomplete installations of the Wagabuild..."
for f in wagabuild*; do
	if [ -d "${f}" ] && [ ! -d "$f/bin" ]; then
		echo "Found incomplete installation at $f/, deleting."
		rm -rf "$f" # is incomplete if bin/ doesn't exist
	fi
done
# ---

# --- ask if you want to delete all remaining WB* folders
echo ""
echo "Would you like to overwrite ALL of your previous installations? (y/N)"
read -r RESP
if [ "$RESP" = "y" ] || [ "$RESP" = "Y" ]; then
	echo "Are you sure? This action is not reversible! (y/N)"
	read -r RESP
	if [ "$RESP" = "y" ] || [ "$RESP" = "Y" ] ; then
		rm -rf wagabuild*/
		echo "Deleted all wb folders!"
	fi
else
	echo "No changes made!"
fi
# ---
	echo ""
	echo "Loading config files Wagabuild - $WBVERSION!"

# Set FOLDERNAME based on WB version
FOLDERNAME="wagabuild-${WBVERSION}"

# --- check for previously installed version, ask if overwrite is wanted
if [ -d "$FOLDERNAME" ]; then
	echo "
	wb Folder with same version found! Would you like to overwrite? (y/N)"
	read -r RESP
	if [ "$RESP" = "y" ] || [ "$RESP" = "Y" ]; then
		echo "Are you sure? This action is not reversible! (y/N)"
		read -r RESP
		if [ "$RESP" = "y" ] || [ "$RESP" = "Y" ] ; then
			rm -r "$FOLDERNAME"
			echo "Deleted!"
		else
			echo "Quitting!"
			exit
		fi
	else
		echo "Quitting!"
		exit
	fi
fi
# ---


# --- prompt to install adapter support
echo "
Would you like to install udev rules for your Wii U adapter? (y/N) (Necessary for reduced-lag direct adapter connection)"
read -r RESP
if [ "$RESP" = "y" ] || [ "$RESP" = "Y" ]; then
	if [ ! -z "${IN_NIX_SHELL++}" ]; then
		echo "please add services.udev.extraRules = ''"
		echo 'SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", ATTRS{idVendor}=="057e", ATTRS{idProduct}=="0337", MODE="0666";'
		echo 'SUBSYSTEMS=="usb", ATTRS{idVendor}=="1209", ATTRS{idProduct}=="2300", SYMLINK+="model01", ENV{ID_MM_DEVICE_IGNORE}:="1", ENV{ID_MM_CANDIDATE}:="0";'
		echo 'SUBSYSTEMS=="usb", ATTRS{idVendor}=="1209", ATTRS{idProduct}=="2301", SYMLINK+="model01", ENV{ID_MM_DEVICE_IGNORE}:="1", ENV{ID_MM_CANDIDATE}:="0";'
		echo "'';"
	else
		sudo rm -f /etc/udev/rules.d/51-gcadapter.rules # remove even if doesn't exist
		echo 'SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", ATTRS{idVendor}=="057e", ATTRS{idProduct}=="0337", MODE="0666"' | sudo tee /etc/udev/rules.d/51-gcadapter.rules > /dev/null # pipe to write-protected file, remove STDOUT
		sudo udevadm control --reload-rules
		echo "Rules added!"
	fi
else
	echo "No changes made!"
fi
# ---

# --- prompt to queue shortcut creation for later
echo "
Would you like to make a desktop shortcut? (Y/n)"
read -r RESP
if [ ! "$RESP" = "n" ] && [ ! "$RESP" = "N" ]; then
	SHORTCUTBOOL=1
	echo "Desktop shortcut queued!"
else
	SHORTCUTBOOL=0
	echo "No changes made!"
fi
# ---

# --- prompt for -j flag (# of cores utilized)
echo ""
echo "CPU Threads detected: $CPUS"
echo "How many threads would you like to use to compile? (passed to make as -j flag, default: $CPUS, range: 1 - $(( CPUS )))"
read -r RESP
if [ "$RESP" -ge 1 ] 2> /dev/null && [ "$RESP" -le $((CPUS + 1)) ] 2> /dev/null; then
	CPUS=$RESP 
else
	CPUS=$CPUS
fi
echo "Using $CPUS thread(s)!"
# ---

# --- enter folder, download and extract needed files
echo ""
mkdir "$FOLDERNAME" && cd "$FOLDERNAME"
echo "Downloading config files..."
curl -LO# $CONFIGLINK
echo "Extracting config files..."
tar -xzf "$WBVERSION-$CONFIGNAME.tar.gz" --checkpoint-action='exec=printf "%d/410 records extracted.\r" $TAR_CHECKPOINT' --totals
rm "$WBVERSION-$CONFIGNAME.tar.gz"
echo ""
echo "Downloading tarball..."
curl -LO# "$GITCLONELINK/archive/$COMMITHASH.tar.gz"
echo "Extracting tarball..."
tar -xzf "$COMMITHASH.tar.gz" --checkpoint-action='exec=printf "%d/12130 records extracted.\r" $TAR_CHECKPOINT' --totals
rm "$COMMITHASH.tar.gz"
echo "" #spacing
mv "dolphin-$COMMITHASH" dolphin
cd dolphin

# --- Patch tarball to display correct hash to other netplay clients
echo "Patching tarball..."
sed -i "s|\${GIT_EXECUTABLE} rev-parse HEAD|echo ${COMMITHASH}|g" CMakeLists.txt  # --set scm_rev_str everywhere to actual commit hash when downloaded
sed -i "s|\${GIT_EXECUTABLE} describe --always --long --dirty|echo Wagabuild $WBVERSION|g" CMakeLists.txt # ensures compatibility w/ netplay
sed -i "s|\${GIT_EXECUTABLE} rev-parse --abbrev-ref HEAD|echo Koopa|g" CMakeLists.txt
# ---

# --- move necessary config files into the build folder
echo "Adding WB config files..."
mkdir build && cd build
mv ../../Binaries .
# ---

# --- cmake and compile
echo "cmaking..."
if [ ! -z "${IN_NIX_SHELL++}" ]; then
	cmake .. -DLINUX_LOCAL_DEV=true -DGTK2_GLIBCONFIG_INCLUDE_DIR=${glib}/lib/glib-2.0/include -DGTK2_GDKCONFIG_INCLUDE_DIR=${gtk2}/lib/gtk-2.0/include -DGTK2_INCLUDE_DIRS=${gtk2}/lib/gtk-2.0 -DENABLE_LTO=True
else
	cmake .. -DLINUX_LOCAL_DEV=true
fi
echo "Compiling..."
make -j $CPUS -s
# ---

# --- Download the sd card tarball, extract it, move it to proper folder, and delete tarball
# credit to https://superuser.com/a/1517096 superuser.com user Zibri
echo "Downloading sd card"
echo "Downloading from StackStorage";
 curl --header "Host: ufopiloot.stackstorage.com" --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0" --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" --header "Accept-Language: en-US,en;q=0.5" --header "Content-Type: application/x-www-form-urlencoded" --header "Origin: https://ufopiloot.stackstorage.com" --referer "https://ufopiloot.stackstorage.com/s/fUqTDzu15KRXNrz" --cookie "stackShareSession=j8eVdF8-zHsL71TGQt88lGk-Uqw" --header "Upgrade-Insecure-Requests: 1" --request POST --data-urlencode "archive=zip" --data-urlencode "all=false" --data-urlencode "CSRF-Token=HJFPMfKTRGh3iRXBDcjZvQ" --data-urlencode "paths%5B%5D=/" "https://ufopiloot.stackstorage.com/public-share/fUqTDzu15KRXNrz/download/" --output "NepPlaySd.tar.gz"


echo "Extracting sd card"
tar -xzf "NepPlaySd.tar.gz" --checkpoint-action='exec=printf "%d/12130 records extracted.\r" $TAR_CHECKPOINT' --totals
mv "nepplay.raw" "Binaries/User/Wii/nepplay.raw"
rm "NepPlaySd.tar.gz"
# ---

# --- Delete created files and old symlinks, isolate Binaries to their own folder
echo "Cleaning up..."
cd ../..
mv dolphin/build/Binaries/ bin/
rm -rf dolphin # -f required to remove git history
rm -f ../launch-wagabuild # -f required if shortcuts do not exist
rm -f ../launch-wb
# ---

# --- Get Main path and Set Up path variables for config/Dolphin.ini 
echo "Setting config paths"
MainDir=$(pwd)"/bin"
LauncherDir=$MainDir"/Launcher"
GamesDir=$MainDir"/Games"
SDPath=$MainDir"/User/Wii/nepplay.raw"
IsoPath=$GamesDir"/RSBE01.iso"
ConfigPath=$MainDir"/User/Config/Dolphin.ini"
# ---

# --- Set LauncherDir, GamesDir, SdCardPath, and Default ISO path in config/Dolphin.ini
sed -i -e "s|LauncherDir|${LauncherDir}|" $ConfigPath
sed -i -e "s|GamesPath|${GamesDir}|" $ConfigPath
sed -i -e "s|SDPath|${SDPath}|" $ConfigPath
sed -i -e "s|ISODirPath|${IsoPath}|" $ConfigPath
# ---

# --- create symlink to newly compiled dolphin-emu. if queued, create shortcut.
echo "Creating shortcuts..."
ln -s "$FOLDERNAME/bin/dolphin-emu" ../launch-wb
if [ "$SHORTCUTBOOL" -eq 1 ] && [ -d ~/.local/share/applications ]; then
	rm -f ~/.local/share/applications/wagabuild-$WBVERSION.desktop # remove old shortcut
	rm -f ~/Desktop/wagabuild-$WBVERSION.desktop
	touch ~/.local/share/applications/wagabuild-$WBVERSION.desktop # fixes very rare tee bug?
	EXEPATH="$(pwd)/bin"
	wbNAME="Wagabuild $WBVERSION"
	echo "[Desktop Entry]
Type=Application
GenericName=Wii/GameCube Emulator
Comment=dolphin fork for SSBPM
Categories=Emulator;Game;
Icon=$EXEPATH/dolphin.png
Keywords=ProjectM;Project M;ProjectPlus;Project Plus;Project+
Version=$WBVERSION
Name=$wbNAME
Exec=$EXEPATH/dolphin-emu" | tee ~/.local/share/applications/wagabuild-$WBVERSION.desktop > /dev/null
	cp ~/.local/share/applications/wagabuild-$WBVERSION.desktop ~/Desktop
	chmod +x ~/Desktop/wagabuild-$WBVERSION.desktop
else
	echo ".local folder not found, skipping desktop shortcut."
fi
# ---

echo ""
echo "***************************************************************************************************"
echo "Done! Run ./launch-wb to run the latest installed version!"
echo "Alternatively, go to Application > Games or your desktop and select the desired version."
echo "Make sure to unplug and replug your adapter before opening Dolphin if adapter rules were installed!"
echo "***************************************************************************************************"
